[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "agno>=2.5.5",
    "alembic>=1.18.4",
    "boto3>=1.42.59",
    "fastapi[standard]>=0.135.1",
    "fireducks>=1.4.4",
    "google-genai>=1.65.0",
    "groq>=1.0.0",
    "langfuse>=3.14.5",
    "mpire>=2.10.2",
    "openai>=2.24.0",
    "python-dotenv>=1.2.2",
    "ragas>=0.4.3",
    "sqlalchemy>=2.0.47",
]

[dependency-groups]
dev = [
    "setuptools>=82.0.0",
]
