"""
Pydantic models for generic_search
Generated by tool_integration_generator.py
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Literal


class GenericSearchRequest(BaseModel):
    """
    Request model for generic_search
    Retrieve variant rows with filters and pagination
    """

    table_name: Literal["nibmg_exome_somatic_variants", "nibmg_wg_somatic_variants", "tcga_exome_somatic_variants", "journal_exome_somatic_variants"] = Field(
        ...,
        description="Source table for variants"
    )
    filters: ComplexFilter = Field(
        ...,
        description="WHERE clause filters (gene, variant_class, etc.)"
    )
    page: Optional[int] = Field(
        default=1,
        description="Page number for pagination"
    )
    page_size: Optional[int] = Field(
        default=10,
        description="Number of results per page"
    )