import json
import asyncio
from langfuse import observe
from agno.utils.log import logger
from agno.workflow import Workflow
from app.api.search import generic_search
from app.agents.search import search_agent
from app.api.aggregate import generic_aggregate
from app.agents.aggregate import aggregate_agent
from typing import Dict, Any, List, AsyncGenerator
from app.agents.synthesizer import synthesizer_agent
from pydantic import BaseModel, Field, ValidationError
from app.agents.orchestrator import orchestrator_agent
from app.agents.aggregate_combination import concate_aggregate_agent
from app.api.aggregate_combination import generic_concatenated_aggregate

# from langtrace_python_sdk.utils.with_root_span import with_langtrace_root_span

# =========================
# PLAN SCHEMA
# =========================


class SimplePlanStep(BaseModel):
    step_id: str = Field(..., description="Unique identifier for this execution step.")
    tool_name: str = Field(
        ..., description="Tool to execute (generic_search, generic_aggregate, etc.)."
    )
    query_context: str = Field(
        ..., description="Instruction describing what this step should execute."
    )
    deps: List[str] = Field(
        default_factory=list,
        description="Step IDs that must complete before this step.",
    )


class SimplePlan(BaseModel):
    plan: List[SimplePlanStep] = Field(
        ..., description="Execution plan represented as a DAG."
    )


# =========================
# API EXECUTION WRAPPER
# =========================


async def execute_api_call(tool_name: str, params: Any, db: Any) -> Any:
    try:
        if tool_name == "generic_search":
            return await generic_search(params.table_name, params.request_body, db)

        elif tool_name == "generic_aggregate":
            return await generic_aggregate(
                table_name=params.table_name,
                request=params.request_body,
                db=db,
            )

        elif tool_name == "generic_concatenated_aggregate":
            return await generic_concatenated_aggregate(
                table_name=params.table_name,
                request=params.request_body,
                db=db,
            )

        return {"error": f"Unknown tool: {tool_name}"}

    except Exception as e:
        logger.exception("DB execution failed")
        return {"error": str(e)}


# =========================
# WORKFLOW
# =========================
DATA_TOOLS = {
    "generic_search",
    "generic_aggregate",
    "generic_concatenated_aggregate",
}

REASONING_TOOLS = {
    "answer_conversational",
}


class VocalResearchWorkflow(Workflow):
    """
    VOCAL Research Pipeline
    ----------------------
    1. Orchestrator → Execution Plan (DAG)
    2. Parallel + Chained Execution
    3. Synthesizer runs at the end
    """

    specialists: Dict[str, Any] = {
        "generic_search": search_agent,
        "generic_aggregate": aggregate_agent,
        "generic_concatenated_aggregate": concate_aggregate_agent,
    }

    def run(self, query: str, db: Any) -> Dict[str, Any]:
        return asyncio.run(self.run_async(query, db))

    async def run_async(self, query: str, db: Any) -> Dict[str, Any]:
        """Non-streaming version for backwards compatibility"""
        final_result = None
        async for event in self.run_stream(query, db):
            if event["type"] == "final":
                final_result = event["data"]
        return final_result if final_result else {"error": "No result produced"}

    # @with_langtrace_root_span()
    @observe(name="vocal_research_workflow")
    async def run_stream(
        self, query: str, db: Any
    ) -> AsyncGenerator[Dict[str, Any], None]:
        """
        Streaming version that yields events as the workflow progresses
        """
        logger.info(f"Starting workflow for query: {query}")

        yield {
            "type": "status",
            "data": {"message": "Starting workflow", "query": query},
        }

        # =========================
        # STEP 1: PLAN
        # =========================
        try:
            yield {
                "type": "status",
                "data": {"message": "Generating execution plan..."},
            }

            plan_response = await asyncio.to_thread(orchestrator_agent.run, query)
            plan = plan_response.content
            logger.info(f"Execution plan validated: {plan}")

            yield {"type": "plan", "data": {"plan": plan.model_dump()}}

        except (ValidationError, json.JSONDecodeError) as e:
            logger.error(f"Planning failed: {e}")
            yield {
                "type": "error",
                "data": {
                    "error": "Invalid execution plan generated by LLM",
                    "details": str(e),
                },
            }
            return

        # =========================
        # STEP 2: SEPARATE DATA AND REASONING STEPS
        # =========================
        data_steps = [step for step in plan.plan if step.tool_name in DATA_TOOLS]
        reasoning_steps = [
            step for step in plan.plan if step.tool_name in REASONING_TOOLS
        ]

        # =========================
        # STEP 3: EXECUTE DATA STEPS (DAG)
        # =========================
        results: Dict[str, Any] = {}
        pending_steps: Dict[str, SimplePlanStep] = {
            step.step_id: step for step in data_steps
        }

        if pending_steps:
            yield {
                "type": "status",
                "data": {"message": "Executing data retrieval steps..."},
            }

            while pending_steps:
                # Find steps whose dependencies are satisfied
                ready_steps = [
                    step
                    for step in pending_steps.values()
                    if all(dep in results for dep in step.deps)
                ]

                if not ready_steps:
                    logger.error("Circular or unresolved dependencies detected")
                    yield {
                        "type": "error",
                        "data": {"error": "Invalid plan: dependency deadlock"},
                    }
                    return

                # Notify about steps being executed
                yield {
                    "type": "status",
                    "data": {
                        "message": f"Executing {len(ready_steps)} step(s) in parallel",
                        "steps": [step.step_id for step in ready_steps],
                    },
                }

                tasks = [
                    self.execute_plan_step(step, results, db) for step in ready_steps
                ]
                outputs = await asyncio.gather(*tasks, return_exceptions=True)

                for step, output in zip(ready_steps, outputs):
                    if isinstance(output, Exception):
                        logger.error(f"Step {step.step_id} failed: {output}")
                        results[step.step_id] = {"error": str(output)}

                        yield {
                            "type": "step_error",
                            "data": {"step_id": step.step_id, "error": str(output)},
                        }
                    else:
                        results[step.step_id] = output

                        yield {
                            "type": "step_complete",
                            "data": {"step_id": step.step_id, "result": output},
                        }

                    pending_steps.pop(step.step_id)

        # =========================
        # STEP 4: RUN SYNTHESIS
        # =========================
        synthesis_result = None

        if reasoning_steps or data_steps:
            yield {
                "type": "status",
                "data": {"message": "Synthesizing final answer..."},
            }

            synthesis_result = await self.run_synthesis(
                query=query,
                data_results=results,
                reasoning_steps=reasoning_steps,
            )

            yield {
                "type": "synthesis_complete",
                "data": {"synthesis": synthesis_result},
            }

        # =========================
        # STEP 5: FINAL RESULT
        # =========================
        final_data = {
            "plan": plan.model_dump(),
            "results": results,
            "synthesis": synthesis_result,
        }
        yield {"type": "final", "data": final_data}

    # =========================
    # SYNTHESIS RUNNER
    # =========================

    async def run_synthesis(
        self,
        query: str,
        data_results: Dict[str, Any],
        reasoning_steps: List[SimplePlanStep],
    ) -> str:
        """
        Run the synthesizer agent as the final step

        Cases:
        1. Plan has only one answer_conversational step → Direct response
        2. Plan has data steps → Synthesize data into answer
        """

        # CASE 1: Single answer_conversational step (no data steps)
        if len(reasoning_steps) == 1 and not data_results:
            step = reasoning_steps[0]
            prompt = f"""
You are a helpful AI assistant. The user asked:

"{query}"

Context from the query plan:
{step.query_context}

Provide a clear, appropriate response to the user's question.
"""

        # CASE 2: Data steps exist → Synthesize results
        else:
            # Prepare data context
            data_context = {}
            for step_id, result in data_results.items():
                tool_name = result.get("tool")

                # Case 1: generic_search → metadata only
                if tool_name == "generic_search":
                    filtered_result = {k: v for k, v in result.items() if k != "result"}

                # Case 2: all other tools → full payload
                else:
                    filtered_result = result

                if filtered_result:
                    data_context[step_id] = filtered_result

            # Include reasoning step contexts if any
            reasoning_context = ""
            if reasoning_steps:
                reasoning_context = "\n\nAdditional Instructions:\n"
                for step in reasoning_steps:
                    reasoning_context += f"- {step.query_context}\n"

            prompt = f"""
You are synthesizing the final answer for the user's query.

User Query:
"{query}"

Data Retrieved:
{json.dumps(data_context, indent=0)}
{reasoning_context}

Provide a clear, comprehensive answer based on the data above. 
Format your response in a user-friendly way that directly addresses their question.
"""

        # Run synthesizer
        response = await asyncio.to_thread(synthesizer_agent.run, prompt)
        return response.content

    # =========================
    # STEP EXECUTION (DATA ONLY)
    # =========================

    async def execute_plan_step(
        self,
        step: SimplePlanStep,
        resolved_results: Dict[str, Any],
        db: Any,
    ) -> Dict[str, Any]:
        logger.info(f"Executing step {step.step_id} ({step.tool_name})")

        # Only DATA tools should reach here
        if step.tool_name in DATA_TOOLS:
            agent = self.specialists[step.tool_name]

            # Resolve {{step_id}} placeholders if any
            context = resolve_context_placeholders(
                context=step.query_context,
                deps=step.deps,
                resolved_results=resolved_results,
            )

            params_response = await asyncio.to_thread(agent.run, context)
            params = params_response.content

            db_result = await execute_api_call(step.tool_name, params, db)

            execution_result = {
                "tool": step.tool_name,
                "step_id": step.step_id,
                "params": params.model_dump(),
                "result": db_result.model_dump(),
            }

            return execution_result

        # This should not happen since we filter steps
        return {
            "step_id": step.step_id,
            "error": f"Unsupported tool in data execution: {step.tool_name}",
        }


def resolve_context_placeholders(
    context: str,
    deps: List[str],
    resolved_results: Dict[str, Any],
) -> str:
    """
    Replace {{step_id}} placeholders in query_context
    with actual results from dependency steps.
    """
    for dep in deps:
        placeholder = f"{{{{{dep}}}}}"

        if placeholder not in context:
            continue

        try:
            value = resolved_results[dep]["result"]
        except KeyError as e:
            raise RuntimeError(f"Missing result for dependency '{dep}'") from e

        # Convert complex objects safely
        if not isinstance(value, str):
            value = json.dumps(value)

        context = context.replace(placeholder, value)

    return context
