import json
import asyncio
from agno.utils.log import logger
from typing import Dict, Any, List
from agno.workflow import Workflow
from app.api.search import generic_search
from app.agents.search import search_agent
from app.api.aggregate import generic_aggregate
from app.agents.aggregate import aggregate_agent
from app.agents.synthesizer import synthesizer_agent
from pydantic import BaseModel, Field, ValidationError
from app.agents.orchestrator import orchestrator_agent
from app.agents.aggregate_combination import concate_aggregate_agent
from app.api.aggregate_combination import generic_concatenated_aggregate


# =========================
# PLAN SCHEMA
# =========================


class SimplePlanStep(BaseModel):
    step_id: str = Field(..., description="Unique identifier for this execution step.")
    tool_name: str = Field(
        ..., description="Tool to execute (generic_search, generic_aggregate, etc.)."
    )
    query_context: str = Field(
        ..., description="Instruction describing what this step should execute."
    )
    deps: List[str] = Field(
        default_factory=list,
        description="Step IDs that must complete before this step.",
    )


class SimplePlan(BaseModel):
    plan: List[SimplePlanStep] = Field(
        ..., description="Execution plan represented as a DAG."
    )


# =========================
# API EXECUTION WRAPPER
# =========================


async def execute_api_call(tool_name: str, params: Any, db: Any) -> Any:
    try:
        if tool_name == "generic_search":
            return await generic_search(params.table_name, params.request_body, db)

        elif tool_name == "generic_aggregate":
            return await generic_aggregate(
                table_name=params.table_name,
                request=params.request_body,
                db=db,
            )

        elif tool_name == "generic_concatenated_aggregate":
            return await generic_concatenated_aggregate(
                table_name=params.table_name,
                request=params.request_body,
                db=db,
            )

        return {"error": f"Unknown tool: {tool_name}"}

    except Exception as e:
        logger.exception("DB execution failed")
        return {"error": str(e)}


# =========================
# WORKFLOW
# =========================
DATA_TOOLS = {
    "generic_search",
    "generic_aggregate",
    "generic_concatenated_aggregate",
}

REASONING_TOOLS = {
    "answer_conversational",
}


class VocalResearchWorkflow(Workflow):
    """
    VOCAL Research Pipeline
    ----------------------
    1. Orchestrator → Execution Plan (DAG)
    2. Parallel + Chained Execution
    3. Structured Results (ready for synthesis)
    """

    specialists: Dict[str, Any] = {
        "generic_search": search_agent,
        "generic_aggregate": aggregate_agent,
        "generic_concatenated_aggregate": concate_aggregate_agent,
    }

    def run(self, query: str, db: Any) -> Dict[str, Any]:
        return asyncio.run(self.run_async(query, db))

    async def run_async(self, query: str, db: Any) -> Dict[str, Any]:
        logger.info(f"Starting workflow for query: {query}")

        # =========================
        # STEP 1: PLAN
        # =========================
        try:
            plan_response = await asyncio.to_thread(orchestrator_agent.run, query)
            plan = plan_response.content
            logger.info(f"Execution plan validated: {plan}")

        except (ValidationError, json.JSONDecodeError) as e:
            logger.error(f"Planning failed: {e}")
            return {"error": "Invalid execution plan generated by LLM"}

        # =========================
        # STEP 2: EXECUTION (DAG)
        # =========================
        # results: Dict[str, Any] = {}
        # pending_steps: Dict[str, SimplePlanStep] = {
        #     step.step_id: step for step in plan.plan
        # }

        # while pending_steps:
        #     # Find steps whose dependencies are satisfied
        #     ready_steps = [
        #         step
        #         for step in pending_steps.values()
        #         if all(dep in results for dep in step.deps)
        #     ]

        #     if not ready_steps:
        #         logger.error("Circular or unresolved dependencies detected")
        #         return {"error": "Invalid plan: dependency deadlock"}

        #     tasks = [self.execute_plan_step(step, results, db) for step in ready_steps]

        #     outputs = await asyncio.gather(*tasks, return_exceptions=True)

        #     for step, output in zip(ready_steps, outputs):
        #         if isinstance(output, Exception):
        #             logger.error(f"Step {step.step_id} failed: {output}")
        #             results[step.step_id] = {"error": str(output)}
        #         else:
        #             results[step.step_id] = output

        #         pending_steps.pop(step.step_id)

        return {
            "plan": plan.model_dump(),
            # "results": results,
        }

    # =========================
    # STEP EXECUTION
    # =========================

    async def execute_plan_step(
        self,
        step: SimplePlanStep,
        resolved_results: Dict[str, Any],
        db: Any,
    ) -> Dict[str, Any]:
        logger.info(f"Executing step {step.step_id} ({step.tool_name})")

        # ---------------------------
        # CASE 1: DATA / DB STEPS
        # ---------------------------
        if step.tool_name in DATA_TOOLS:
            agent = self.specialists[step.tool_name]

            # Resolve {{step_id}} placeholders if any
            context = resolve_context_placeholders(
                context=step.query_context,
                deps=step.deps,
                resolved_results=resolved_results,
            )

            params_response = await asyncio.to_thread(agent.run, context)
            params = params_response.content

            db_result = await execute_api_call(step.tool_name, params, db)

            return {
                "step_id": step.step_id,
                "tool": step.tool_name,
                "params": params,
                "result": db_result,
            }

        # ---------------------------
        # CASE 2: REASONING / CHAT STEPS
        # ---------------------------
        if step.tool_name in REASONING_TOOLS:
            # Build a clean reasoning context
            dependency_context = {
                dep: resolved_results[dep]["result"].result for dep in step.deps
            }

            reasoning_prompt = f"""
                You are given results from previous analysis steps.

                Previous Results:
                {json.dumps(dependency_context, indent=2)}

                Instruction:
                {step.query_context}

                Provide a clear, concise answer.
            """

            response = await asyncio.to_thread(synthesizer_agent.run, reasoning_prompt)

            return {
                "step_id": step.step_id,
                "tool": step.tool_name,
                "result": response.content,
            }

        # ---------------------------
        # UNKNOWN TOOL
        # ---------------------------
        return {
            "step_id": step.step_id,
            "error": f"Unsupported tool: {step.tool_name}",
        }


def resolve_context_placeholders(
    context: str,
    deps: List[str],
    resolved_results: Dict[str, Any],
) -> str:
    """
    Replace {{step_id}} placeholders in query_context
    with actual results from dependency steps.
    """
    for dep in deps:
        placeholder = f"{{{{{dep}}}}}"

        if placeholder not in context:
            continue

        try:
            value = resolved_results[dep]["result"].result
        except KeyError as e:
            raise RuntimeError(f"Missing result for dependency '{dep}'") from e

        # Convert complex objects safely
        if not isinstance(value, str):
            value = json.dumps(value)

        context = context.replace(placeholder, value)

    return context
