"""modified genomic autocomplete table

Revision ID: 059fab0de0aa
Revises: 53fb2cf94d14
Create Date: 2025-11-01 19:22:56.565817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059fab0de0aa'
down_revision: Union[str, Sequence[str], None] = '53fb2cf94d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('somatic_genomic_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('index_somatic_genomic_position_chr_pos'))
        batch_op.drop_index(batch_op.f('ix_somatic_genomic_position_position'))
        batch_op.create_index('index_somatic_genomic_position_chrom_start', ['chromosome', 'start'], unique=False)
        batch_op.create_index('index_somatic_genomic_position_chrom_start_end', ['chromosome', 'start', 'end'], unique=False)
        batch_op.create_index(batch_op.f('ix_somatic_genomic_position_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_somatic_genomic_position_start'), ['start'], unique=False)
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('somatic_genomic_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_somatic_genomic_position_start'))
        batch_op.drop_index(batch_op.f('ix_somatic_genomic_position_end'))
        batch_op.drop_index('index_somatic_genomic_position_chrom_start_end')
        batch_op.drop_index('index_somatic_genomic_position_chrom_start')
        batch_op.create_index(batch_op.f('ix_somatic_genomic_position_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('index_somatic_genomic_position_chr_pos'), ['chromosome', 'position'], unique=False)
        batch_op.drop_column('start')
        batch_op.drop_column('end')

    # ### end Alembic commands ###
