"""Update oncoplot tables

Revision ID: 1a50b0d256fb
Revises: ba33c8685dae
Create Date: 2025-10-28 01:11:36.887278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a50b0d256fb'
down_revision: Union[str, Sequence[str], None] = 'ba33c8685dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.drop_column('count')

    with op.batch_alter_table('nibmg_exome_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.drop_column('count')

    with op.batch_alter_table('nibmg_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.drop_column('count')

    with op.batch_alter_table('nibmg_wg_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.drop_column('count')

    with op.batch_alter_table('nibmg_wg_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.drop_column('count')

    with op.batch_alter_table('tcga_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tcga_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('code')

    with op.batch_alter_table('nibmg_wg_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('code')

    with op.batch_alter_table('nibmg_wg_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('code')

    with op.batch_alter_table('nibmg_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('code')

    with op.batch_alter_table('nibmg_exome_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('code')

    with op.batch_alter_table('journal_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
