"""Adding necessary index

Revision ID: 32347bc95582
Revises: e36dfc9f1b6e
Create Date: 2025-10-25 10:59:06.990839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32347bc95582'
down_revision: Union[str, Sequence[str], None] = 'e36dfc9f1b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('es_journal_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_es_journal_oncoplot_gene'), ['gene'], unique=False)

    with op.batch_alter_table('es_tcga_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_es_tcga_oncoplot_gene'), ['gene'], unique=False)

    with op.batch_alter_table('exome_germline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exome_germline_sample_id'))
        batch_op.create_index(batch_op.f('ix_exome_germline_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    with op.batch_alter_table('exome_germline_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exome_germline_oncoplot_gene'), ['gene'], unique=False)

    with op.batch_alter_table('exome_somatic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exome_somatic_sample_id'))
        batch_op.create_index(batch_op.f('ix_exome_somatic_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    with op.batch_alter_table('exome_somatic_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exome_somatic_oncoplot_gene'), ['gene'], unique=False)

    with op.batch_alter_table('targeted_germline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targeted_germline_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_germline_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_germline_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_germline_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_germline_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    with op.batch_alter_table('targeted_somatic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targeted_somatic_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_somatic_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_somatic_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_somatic_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_targeted_somatic_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    with op.batch_alter_table('wg_germline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wg_germline_sample_id'))
        batch_op.create_index(batch_op.f('ix_wg_germline_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    with op.batch_alter_table('wg_germline_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wg_germline_oncoplot_gene'), ['gene'], unique=False)

    with op.batch_alter_table('wg_somatic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wg_somatic_sample_id'))
        batch_op.create_index(batch_op.f('ix_wg_somatic_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    with op.batch_alter_table('wg_somatic_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wg_somatic_oncoplot_gene'), ['gene'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wg_somatic_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wg_somatic_oncoplot_gene'))

    with op.batch_alter_table('wg_somatic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wg_somatic_tumor_sample_barcode'))
        batch_op.create_index(batch_op.f('ix_wg_somatic_sample_id'), ['sample_id'], unique=False)

    with op.batch_alter_table('wg_germline_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wg_germline_oncoplot_gene'))

    with op.batch_alter_table('wg_germline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wg_germline_tumor_sample_barcode'))
        batch_op.create_index(batch_op.f('ix_wg_germline_sample_id'), ['sample_id'], unique=False)

    with op.batch_alter_table('targeted_somatic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targeted_somatic_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_targeted_somatic_start'))
        batch_op.drop_index(batch_op.f('ix_targeted_somatic_gene'))
        batch_op.drop_index(batch_op.f('ix_targeted_somatic_end'))
        batch_op.drop_index(batch_op.f('ix_targeted_somatic_chrom'))

    with op.batch_alter_table('targeted_germline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targeted_germline_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_targeted_germline_start'))
        batch_op.drop_index(batch_op.f('ix_targeted_germline_gene'))
        batch_op.drop_index(batch_op.f('ix_targeted_germline_end'))
        batch_op.drop_index(batch_op.f('ix_targeted_germline_chrom'))

    with op.batch_alter_table('exome_somatic_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exome_somatic_oncoplot_gene'))

    with op.batch_alter_table('exome_somatic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exome_somatic_tumor_sample_barcode'))
        batch_op.create_index(batch_op.f('ix_exome_somatic_sample_id'), ['sample_id'], unique=False)

    with op.batch_alter_table('exome_germline_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exome_germline_oncoplot_gene'))

    with op.batch_alter_table('exome_germline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exome_germline_tumor_sample_barcode'))
        batch_op.create_index(batch_op.f('ix_exome_germline_sample_id'), ['sample_id'], unique=False)

    with op.batch_alter_table('es_tcga_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_es_tcga_oncoplot_gene'))

    with op.batch_alter_table('es_journal_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_es_journal_oncoplot_gene'))

    # ### end Alembic commands ###
