"""Test1

Revision ID: 57ad68254727
Revises: 8bed35cf0a1b
Create Date: 2025-08-11 17:23:20.637569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ad68254727'
down_revision: Union[str, Sequence[str], None] = '8bed35cf0a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('es_journal',
    sa.Column('esj_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('esj_id')
    )
    op.create_index(op.f('ix_es_journal_chrom'), 'es_journal', ['chrom'], unique=False)
    op.create_index(op.f('ix_es_journal_end'), 'es_journal', ['end'], unique=False)
    op.create_index(op.f('ix_es_journal_start'), 'es_journal', ['start'], unique=False)
    op.create_index(op.f('ix_es_journal_tumor_sample_barcode'), 'es_journal', ['tumor_sample_barcode'], unique=False)
    op.create_table('es_tcga',
    sa.Column('tcga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tcga_id')
    )
    op.create_index(op.f('ix_es_tcga_chrom'), 'es_tcga', ['chrom'], unique=False)
    op.create_index(op.f('ix_es_tcga_end'), 'es_tcga', ['end'], unique=False)
    op.create_index(op.f('ix_es_tcga_gene'), 'es_tcga', ['gene'], unique=False)
    op.create_index(op.f('ix_es_tcga_start'), 'es_tcga', ['start'], unique=False)
    op.create_index(op.f('ix_es_tcga_tumor_sample_barcode'), 'es_tcga', ['tumor_sample_barcode'], unique=False)
    op.create_table('exome_germline',
    sa.Column('egm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=3), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=10), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('egm_id')
    )
    op.create_index(op.f('ix_exome_germline_chrom'), 'exome_germline', ['chrom'], unique=False)
    op.create_index(op.f('ix_exome_germline_end'), 'exome_germline', ['end'], unique=False)
    op.create_index(op.f('ix_exome_germline_gene'), 'exome_germline', ['gene'], unique=False)
    op.create_index(op.f('ix_exome_germline_sample_id'), 'exome_germline', ['sample_id'], unique=False)
    op.create_index(op.f('ix_exome_germline_start'), 'exome_germline', ['start'], unique=False)
    op.create_table('exome_somatic',
    sa.Column('esm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=3), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=10), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('esm_id')
    )
    op.create_index(op.f('ix_exome_somatic_chrom'), 'exome_somatic', ['chrom'], unique=False)
    op.create_index(op.f('ix_exome_somatic_end'), 'exome_somatic', ['end'], unique=False)
    op.create_index(op.f('ix_exome_somatic_gene'), 'exome_somatic', ['gene'], unique=False)
    op.create_index(op.f('ix_exome_somatic_sample_id'), 'exome_somatic', ['sample_id'], unique=False)
    op.create_index(op.f('ix_exome_somatic_start'), 'exome_somatic', ['start'], unique=False)
    op.create_table('genelist',
    sa.Column('gene', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('gene')
    )
    op.create_table('pathway',
    sa.Column('path_id', sa.String(length=12), nullable=False),
    sa.Column('pathway_name', sa.String(length=300), nullable=True),
    sa.Column('path_gene', sa.String(length=6000), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('samplelist',
    sa.Column('sample_id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('targeted_germline',
    sa.Column('tgm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=3), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=10), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('tgm_id')
    )
    op.create_table('targeted_somatic',
    sa.Column('tsm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=3), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=10), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('tsm_id')
    )
    op.create_table('uniprot_fixed',
    sa.Column('Row_Index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Hugo_Symbol', sa.String(length=20), nullable=True),
    sa.Column('Accession_Id', sa.String(length=20), nullable=True),
    sa.Column('Structure', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Row_Index')
    )
    op.create_table('wg_germline',
    sa.Column('wgm_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=3), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=10), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('wgm_id')
    )
    op.create_index(op.f('ix_wg_germline_chrom'), 'wg_germline', ['chrom'], unique=False)
    op.create_index(op.f('ix_wg_germline_end'), 'wg_germline', ['end'], unique=False)
    op.create_index(op.f('ix_wg_germline_gene'), 'wg_germline', ['gene'], unique=False)
    op.create_index(op.f('ix_wg_germline_sample_id'), 'wg_germline', ['sample_id'], unique=False)
    op.create_index(op.f('ix_wg_germline_start'), 'wg_germline', ['start'], unique=False)
    op.create_table('wg_somatic',
    sa.Column('wsm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=3), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=10), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('wsm_id')
    )
    op.create_index(op.f('ix_wg_somatic_chrom'), 'wg_somatic', ['chrom'], unique=False)
    op.create_index(op.f('ix_wg_somatic_end'), 'wg_somatic', ['end'], unique=False)
    op.create_index(op.f('ix_wg_somatic_gene'), 'wg_somatic', ['gene'], unique=False)
    op.create_index(op.f('ix_wg_somatic_sample_id'), 'wg_somatic', ['sample_id'], unique=False)
    op.create_index(op.f('ix_wg_somatic_start'), 'wg_somatic', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wg_somatic_start'), table_name='wg_somatic')
    op.drop_index(op.f('ix_wg_somatic_sample_id'), table_name='wg_somatic')
    op.drop_index(op.f('ix_wg_somatic_gene'), table_name='wg_somatic')
    op.drop_index(op.f('ix_wg_somatic_end'), table_name='wg_somatic')
    op.drop_index(op.f('ix_wg_somatic_chrom'), table_name='wg_somatic')
    op.drop_table('wg_somatic')
    op.drop_index(op.f('ix_wg_germline_start'), table_name='wg_germline')
    op.drop_index(op.f('ix_wg_germline_sample_id'), table_name='wg_germline')
    op.drop_index(op.f('ix_wg_germline_gene'), table_name='wg_germline')
    op.drop_index(op.f('ix_wg_germline_end'), table_name='wg_germline')
    op.drop_index(op.f('ix_wg_germline_chrom'), table_name='wg_germline')
    op.drop_table('wg_germline')
    op.drop_table('uniprot_fixed')
    op.drop_table('targeted_somatic')
    op.drop_table('targeted_germline')
    op.drop_table('samplelist')
    op.drop_table('pathway')
    op.drop_table('genelist')
    op.drop_index(op.f('ix_exome_somatic_start'), table_name='exome_somatic')
    op.drop_index(op.f('ix_exome_somatic_sample_id'), table_name='exome_somatic')
    op.drop_index(op.f('ix_exome_somatic_gene'), table_name='exome_somatic')
    op.drop_index(op.f('ix_exome_somatic_end'), table_name='exome_somatic')
    op.drop_index(op.f('ix_exome_somatic_chrom'), table_name='exome_somatic')
    op.drop_table('exome_somatic')
    op.drop_index(op.f('ix_exome_germline_start'), table_name='exome_germline')
    op.drop_index(op.f('ix_exome_germline_sample_id'), table_name='exome_germline')
    op.drop_index(op.f('ix_exome_germline_gene'), table_name='exome_germline')
    op.drop_index(op.f('ix_exome_germline_end'), table_name='exome_germline')
    op.drop_index(op.f('ix_exome_germline_chrom'), table_name='exome_germline')
    op.drop_table('exome_germline')
    op.drop_index(op.f('ix_es_tcga_tumor_sample_barcode'), table_name='es_tcga')
    op.drop_index(op.f('ix_es_tcga_start'), table_name='es_tcga')
    op.drop_index(op.f('ix_es_tcga_gene'), table_name='es_tcga')
    op.drop_index(op.f('ix_es_tcga_end'), table_name='es_tcga')
    op.drop_index(op.f('ix_es_tcga_chrom'), table_name='es_tcga')
    op.drop_table('es_tcga')
    op.drop_index(op.f('ix_es_journal_tumor_sample_barcode'), table_name='es_journal')
    op.drop_index(op.f('ix_es_journal_start'), table_name='es_journal')
    op.drop_index(op.f('ix_es_journal_end'), table_name='es_journal')
    op.drop_index(op.f('ix_es_journal_chrom'), table_name='es_journal')
    op.drop_table('es_journal')
    # ### end Alembic commands ###
