"""Adding es_tcga_somaticvaration1

Revision ID: 6630ed780d6e
Revises: 32347bc95582
Create Date: 2025-10-25 11:24:00.994498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6630ed780d6e'
down_revision: Union[str, Sequence[str], None] = '32347bc95582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('es_tcga_somatic_variation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene1', sa.String(length=20), nullable=True),
    sa.Column('gene2', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('neg_log10_pval', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('es_tcga_somatic_variation', schema=None) as batch_op:
        batch_op.create_index('ix_es_tcga_somatic_variation_gene1_gene2', ['gene1', 'gene2'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('es_tcga_somatic_variation', schema=None) as batch_op:
        batch_op.drop_index('ix_es_tcga_somatic_variation_gene1_gene2')

    op.drop_table('es_tcga_somatic_variation')
    # ### end Alembic commands ###
