"""Add oncoplot tables

Revision ID: 8b5a4c0bb0b6
Revises: 57ad68254727
Create Date: 2025-10-23 16:40:20.021195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5a4c0bb0b6'
down_revision: Union[str, Sequence[str], None] = '57ad68254727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('es_tcga_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('evalue', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exome_germline_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('evalue', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exome_somatic_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('evalue', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wg_germline_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('evalue', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wg_somatic_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('evalue', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('es_journal', schema=None) as batch_op:
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('es_journal', schema=None) as batch_op:
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('wg_somatic_oncoplot')
    op.drop_table('wg_germline_oncoplot')
    op.drop_table('exome_somatic_oncoplot')
    op.drop_table('exome_germline_oncoplot')
    op.drop_table('es_tcga_oncoplot')
    # ### end Alembic commands ###
