"""new

Revision ID: 9161b7da2f47
Revises: 
Create Date: 2026-03-02 13:32:51.230519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9161b7da2f47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('user_identifier', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('ip_whitelist', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token'), ['token'], unique=True)

    op.create_table('genelist',
    sa.Column('gene', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('gene')
    )
    op.create_table('pathway',
    sa.Column('pathway_name', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_barcode',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('somatic_genomic_position',
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chromosome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('somatic_genomic_position', schema=None) as batch_op:
        batch_op.create_index('index_somatic_genomic_position_chrom_start', ['chromosome', 'start'], unique=False)
        batch_op.create_index('index_somatic_genomic_position_chrom_start_end', ['chromosome', 'start', 'end'], unique=False)
        batch_op.create_index(batch_op.f('ix_somatic_genomic_position_chromosome'), ['chromosome'], unique=False)
        batch_op.create_index(batch_op.f('ix_somatic_genomic_position_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_somatic_genomic_position_start'), ['start'], unique=False)

    op.create_table('pathway_gene_association',
    sa.Column('gene', sa.String(length=200), nullable=True),
    sa.Column('pathway_id', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathway.id'], )
    )
    op.create_table('transcript_data',
    sa.Column('gene_id', sa.String(length=20), nullable=True),
    sa.Column('refseq_id', sa.String(length=20), nullable=True),
    sa.Column('protein_id', sa.String(length=20), nullable=True),
    sa.Column('uniprot_id', sa.String(length=20), nullable=True),
    sa.Column('protein_length', sa.Integer(), nullable=True),
    sa.Column('transcript_id', sa.String(length=50), nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    with op.batch_alter_table('transcript_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_data_gene'), ['gene'], unique=False)

    op.create_table('uniprot_structure',
    sa.Column('structure', sa.Text(), nullable=True),
    sa.Column('accession_id', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uniprot_structure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uniprot_structure_gene'), ['gene'], unique=False)

    op.create_table('variant_data',
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('trinucleotide_context', sa.String(length=3), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    with op.batch_alter_table('variant_data', schema=None) as batch_op:
        batch_op.create_index('idx_variant_data_dataset_chrom_start', ['table_name', 'chrom', 'start'], unique=False)
        batch_op.create_index('idx_variant_data_dataset_chrom_start_end', ['table_name', 'chrom', 'start', 'end'], unique=False)
        batch_op.create_index('idx_variant_data_dataset_gene', ['table_name', 'gene'], unique=False)
        batch_op.create_index('idx_variant_data_dataset_varianttype', ['table_name', 'variant_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_variant_data_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_variant_data_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('domain_data',
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('domain_name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('transcript_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript_data.transcript_id'], ),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    with op.batch_alter_table('domain_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_data_transcript_id'), ['transcript_id'], unique=False)

    op.create_table('exon_data',
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('strand', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('exon_id', sa.String(length=20), nullable=True),
    sa.Column('transcript_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript_data.transcript_id'], ),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    with op.batch_alter_table('exon_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exon_data_transcript_id'), ['transcript_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exon_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exon_data_transcript_id'))

    op.drop_table('exon_data')
    with op.batch_alter_table('domain_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_data_transcript_id'))

    op.drop_table('domain_data')
    with op.batch_alter_table('variant_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variant_data_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_variant_data_gene'))
        batch_op.drop_index('idx_variant_data_dataset_varianttype')
        batch_op.drop_index('idx_variant_data_dataset_gene')
        batch_op.drop_index('idx_variant_data_dataset_chrom_start_end')
        batch_op.drop_index('idx_variant_data_dataset_chrom_start')

    op.drop_table('variant_data')
    with op.batch_alter_table('uniprot_structure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uniprot_structure_gene'))

    op.drop_table('uniprot_structure')
    with op.batch_alter_table('transcript_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_data_gene'))

    op.drop_table('transcript_data')
    op.drop_table('pathway_gene_association')
    with op.batch_alter_table('somatic_genomic_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_somatic_genomic_position_start'))
        batch_op.drop_index(batch_op.f('ix_somatic_genomic_position_end'))
        batch_op.drop_index(batch_op.f('ix_somatic_genomic_position_chromosome'))
        batch_op.drop_index('index_somatic_genomic_position_chrom_start_end')
        batch_op.drop_index('index_somatic_genomic_position_chrom_start')

    op.drop_table('somatic_genomic_position')
    op.drop_table('patient_barcode')
    op.drop_table('pathway')
    op.drop_table('genelist')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_token'))

    op.drop_table('api_tokens')
    # ### end Alembic commands ###
