"""Create Tables

Revision ID: ba33c8685dae
Revises: 
Create Date: 2025-10-27 21:02:18.313800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba33c8685dae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('user_identifier', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('ip_whitelist', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token'), ['token'], unique=True)

    op.create_table('genelist',
    sa.Column('gene', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('gene')
    )
    op.create_table('pathway',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('pathway_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_barcode',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_exome_somatic_gene_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene1', sa.String(length=20), nullable=True),
    sa.Column('gene2', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('neg_log10_pval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gene1'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['gene2'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_exome_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.create_index('index_journal_exome_somatic_gene_interation', ['gene1', 'gene2'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_gene_interaction_gene1'), ['gene1'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_gene_interaction_gene2'), ['gene2'], unique=False)

    op.create_table('journal_exome_somatic_sample_titv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('snv_class', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_exome_somatic_sample_titv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_sample_titv_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('journal_exome_somatic_sample_tmb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_exome_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_sample_tmb_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('journal_exome_somatic_variant_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_variant_oncoplot_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_variant_oncoplot_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('journal_exome_somatic_variants',
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    with op.batch_alter_table('journal_exome_somatic_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_variants_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_variants_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_variants_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_variants_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_exome_somatic_variants_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_germline_gene_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene1', sa.String(length=20), nullable=True),
    sa.Column('gene2', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('neg_log10_pval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gene1'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['gene2'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_germline_gene_interaction', schema=None) as batch_op:
        batch_op.create_index('index_nibmg_exome_germline_gene_interation', ['gene1', 'gene2'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_gene_interaction_gene1'), ['gene1'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_gene_interaction_gene2'), ['gene2'], unique=False)

    op.create_table('nibmg_exome_germline_sample_titv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('snv_class', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_germline_sample_titv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_sample_titv_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_germline_sample_tmb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_germline_sample_tmb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_sample_tmb_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_germline_variant_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_variant_oncoplot_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_variant_oncoplot_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_germline_variants',
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    with op.batch_alter_table('nibmg_exome_germline_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_variants_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_variants_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_variants_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_variants_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_germline_variants_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_somatic_gene_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene1', sa.String(length=20), nullable=True),
    sa.Column('gene2', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('neg_log10_pval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gene1'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['gene2'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.create_index('index_nibmg_exome_somatic_gene_interation', ['gene1', 'gene2'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_gene_interaction_gene1'), ['gene1'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_gene_interaction_gene2'), ['gene2'], unique=False)

    op.create_table('nibmg_exome_somatic_sample_titv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('snv_class', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_somatic_sample_titv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_sample_titv_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_somatic_sample_tmb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_sample_tmb_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_somatic_variant_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_variant_oncoplot_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_variant_oncoplot_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_exome_somatic_variants',
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    with op.batch_alter_table('nibmg_exome_somatic_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_variants_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_variants_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_variants_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_variants_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_exome_somatic_variants_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_germline_gene_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene1', sa.String(length=20), nullable=True),
    sa.Column('gene2', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('neg_log10_pval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gene1'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['gene2'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_germline_gene_interaction', schema=None) as batch_op:
        batch_op.create_index('index_nibmg_wg_germline_gene_interation', ['gene1', 'gene2'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_gene_interaction_gene1'), ['gene1'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_gene_interaction_gene2'), ['gene2'], unique=False)

    op.create_table('nibmg_wg_germline_sample_titv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('snv_class', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_germline_sample_titv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_sample_titv_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_germline_sample_tmb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_germline_sample_tmb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_sample_tmb_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_germline_variant_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_variant_oncoplot_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_variant_oncoplot_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_germline_variants',
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    with op.batch_alter_table('nibmg_wg_germline_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_variants_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_variants_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_variants_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_variants_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_germline_variants_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_somatic_gene_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene1', sa.String(length=20), nullable=True),
    sa.Column('gene2', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('neg_log10_pval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gene1'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['gene2'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.create_index('index_nibmg_wg_somatic_gene_interation', ['gene1', 'gene2'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_gene_interaction_gene1'), ['gene1'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_gene_interaction_gene2'), ['gene2'], unique=False)

    op.create_table('nibmg_wg_somatic_sample_titv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('snv_class', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_somatic_sample_titv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_sample_titv_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_somatic_sample_tmb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_sample_tmb_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_somatic_variant_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nibmg_wg_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_variant_oncoplot_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_variant_oncoplot_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('nibmg_wg_somatic_variants',
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    with op.batch_alter_table('nibmg_wg_somatic_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_variants_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_variants_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_variants_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_variants_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_nibmg_wg_somatic_variants_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('pathway_gene_association',
    sa.Column('gene', sa.String(length=200), nullable=True),
    sa.Column('pathway_id', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathway.id'], )
    )
    op.create_table('tcga_exome_somatic_gene_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene1', sa.String(length=20), nullable=True),
    sa.Column('gene2', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('neg_log10_pval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gene1'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['gene2'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tcga_exome_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.create_index('index_tcga_exome_somatic_gene_interation', ['gene1', 'gene2'], unique=False)
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_gene_interaction_gene1'), ['gene1'], unique=False)
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_gene_interaction_gene2'), ['gene2'], unique=False)

    op.create_table('tcga_exome_somatic_sample_titv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('snv_class', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tcga_exome_somatic_sample_titv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_sample_titv_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('tcga_exome_somatic_sample_tmb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tcga_exome_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_sample_tmb_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('tcga_exome_somatic_variant_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tcga_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_variant_oncoplot_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_variant_oncoplot_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('tcga_exome_somatic_variants',
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('entrez_gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_build', sa.String(length=6), nullable=True),
    sa.Column('chrom', sa.String(length=6), nullable=True),
    sa.Column('start', sa.String(length=30), nullable=True),
    sa.Column('end', sa.String(length=30), nullable=True),
    sa.Column('variant_class', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=10), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('tumor_seq_allele2', sa.String(length=50), nullable=True),
    sa.Column('dbsnp_rs', sa.String(length=200), nullable=True),
    sa.Column('tumor_sample_barcode', sa.String(length=20), nullable=True),
    sa.Column('genome_change', sa.String(length=75), nullable=True),
    sa.Column('annotation_transcript', sa.String(length=20), nullable=True),
    sa.Column('transcript_strand', sa.String(length=2), nullable=True),
    sa.Column('transcript_exon', sa.String(length=10), nullable=True),
    sa.Column('transcript_position', sa.String(length=20), nullable=True),
    sa.Column('cDNA_change', sa.String(length=30), nullable=True),
    sa.Column('codon_change', sa.String(length=30), nullable=True),
    sa.Column('protein_change', sa.String(length=20), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('reference_url', sa.String(length=900), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.ForeignKeyConstraint(['tumor_sample_barcode'], ['patient_barcode.id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    with op.batch_alter_table('tcga_exome_somatic_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_variants_chrom'), ['chrom'], unique=False)
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_variants_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_variants_gene'), ['gene'], unique=False)
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_variants_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_tcga_exome_somatic_variants_tumor_sample_barcode'), ['tumor_sample_barcode'], unique=False)

    op.create_table('uniprot_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('accession_id', sa.String(length=20), nullable=True),
    sa.Column('structure', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gene'], ['genelist.gene'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uniprot_structure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uniprot_structure_gene'), ['gene'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uniprot_structure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uniprot_structure_gene'))

    op.drop_table('uniprot_structure')
    with op.batch_alter_table('tcga_exome_somatic_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_variants_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_variants_start'))
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_variants_gene'))
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_variants_end'))
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_variants_chrom'))

    op.drop_table('tcga_exome_somatic_variants')
    with op.batch_alter_table('tcga_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_variant_oncoplot_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_variant_oncoplot_gene'))

    op.drop_table('tcga_exome_somatic_variant_oncoplot')
    with op.batch_alter_table('tcga_exome_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_sample_tmb_tumor_sample_barcode'))

    op.drop_table('tcga_exome_somatic_sample_tmb')
    with op.batch_alter_table('tcga_exome_somatic_sample_titv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_sample_titv_tumor_sample_barcode'))

    op.drop_table('tcga_exome_somatic_sample_titv')
    with op.batch_alter_table('tcga_exome_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_gene_interaction_gene2'))
        batch_op.drop_index(batch_op.f('ix_tcga_exome_somatic_gene_interaction_gene1'))
        batch_op.drop_index('index_tcga_exome_somatic_gene_interation')

    op.drop_table('tcga_exome_somatic_gene_interaction')
    op.drop_table('pathway_gene_association')
    with op.batch_alter_table('nibmg_wg_somatic_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_variants_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_variants_start'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_variants_gene'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_variants_end'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_variants_chrom'))

    op.drop_table('nibmg_wg_somatic_variants')
    with op.batch_alter_table('nibmg_wg_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_variant_oncoplot_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_variant_oncoplot_gene'))

    op.drop_table('nibmg_wg_somatic_variant_oncoplot')
    with op.batch_alter_table('nibmg_wg_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_sample_tmb_tumor_sample_barcode'))

    op.drop_table('nibmg_wg_somatic_sample_tmb')
    with op.batch_alter_table('nibmg_wg_somatic_sample_titv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_sample_titv_tumor_sample_barcode'))

    op.drop_table('nibmg_wg_somatic_sample_titv')
    with op.batch_alter_table('nibmg_wg_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_gene_interaction_gene2'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_somatic_gene_interaction_gene1'))
        batch_op.drop_index('index_nibmg_wg_somatic_gene_interation')

    op.drop_table('nibmg_wg_somatic_gene_interaction')
    with op.batch_alter_table('nibmg_wg_germline_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_variants_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_variants_start'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_variants_gene'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_variants_end'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_variants_chrom'))

    op.drop_table('nibmg_wg_germline_variants')
    with op.batch_alter_table('nibmg_wg_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_variant_oncoplot_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_variant_oncoplot_gene'))

    op.drop_table('nibmg_wg_germline_variant_oncoplot')
    with op.batch_alter_table('nibmg_wg_germline_sample_tmb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_sample_tmb_tumor_sample_barcode'))

    op.drop_table('nibmg_wg_germline_sample_tmb')
    with op.batch_alter_table('nibmg_wg_germline_sample_titv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_sample_titv_tumor_sample_barcode'))

    op.drop_table('nibmg_wg_germline_sample_titv')
    with op.batch_alter_table('nibmg_wg_germline_gene_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_gene_interaction_gene2'))
        batch_op.drop_index(batch_op.f('ix_nibmg_wg_germline_gene_interaction_gene1'))
        batch_op.drop_index('index_nibmg_wg_germline_gene_interation')

    op.drop_table('nibmg_wg_germline_gene_interaction')
    with op.batch_alter_table('nibmg_exome_somatic_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_variants_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_variants_start'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_variants_gene'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_variants_end'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_variants_chrom'))

    op.drop_table('nibmg_exome_somatic_variants')
    with op.batch_alter_table('nibmg_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_variant_oncoplot_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_variant_oncoplot_gene'))

    op.drop_table('nibmg_exome_somatic_variant_oncoplot')
    with op.batch_alter_table('nibmg_exome_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_sample_tmb_tumor_sample_barcode'))

    op.drop_table('nibmg_exome_somatic_sample_tmb')
    with op.batch_alter_table('nibmg_exome_somatic_sample_titv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_sample_titv_tumor_sample_barcode'))

    op.drop_table('nibmg_exome_somatic_sample_titv')
    with op.batch_alter_table('nibmg_exome_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_gene_interaction_gene2'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_somatic_gene_interaction_gene1'))
        batch_op.drop_index('index_nibmg_exome_somatic_gene_interation')

    op.drop_table('nibmg_exome_somatic_gene_interaction')
    with op.batch_alter_table('nibmg_exome_germline_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_variants_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_variants_start'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_variants_gene'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_variants_end'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_variants_chrom'))

    op.drop_table('nibmg_exome_germline_variants')
    with op.batch_alter_table('nibmg_exome_germline_variant_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_variant_oncoplot_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_variant_oncoplot_gene'))

    op.drop_table('nibmg_exome_germline_variant_oncoplot')
    with op.batch_alter_table('nibmg_exome_germline_sample_tmb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_sample_tmb_tumor_sample_barcode'))

    op.drop_table('nibmg_exome_germline_sample_tmb')
    with op.batch_alter_table('nibmg_exome_germline_sample_titv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_sample_titv_tumor_sample_barcode'))

    op.drop_table('nibmg_exome_germline_sample_titv')
    with op.batch_alter_table('nibmg_exome_germline_gene_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_gene_interaction_gene2'))
        batch_op.drop_index(batch_op.f('ix_nibmg_exome_germline_gene_interaction_gene1'))
        batch_op.drop_index('index_nibmg_exome_germline_gene_interation')

    op.drop_table('nibmg_exome_germline_gene_interaction')
    with op.batch_alter_table('journal_exome_somatic_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_variants_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_variants_start'))
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_variants_gene'))
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_variants_end'))
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_variants_chrom'))

    op.drop_table('journal_exome_somatic_variants')
    with op.batch_alter_table('journal_exome_somatic_variant_oncoplot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_variant_oncoplot_tumor_sample_barcode'))
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_variant_oncoplot_gene'))

    op.drop_table('journal_exome_somatic_variant_oncoplot')
    with op.batch_alter_table('journal_exome_somatic_sample_tmb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_sample_tmb_tumor_sample_barcode'))

    op.drop_table('journal_exome_somatic_sample_tmb')
    with op.batch_alter_table('journal_exome_somatic_sample_titv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_sample_titv_tumor_sample_barcode'))

    op.drop_table('journal_exome_somatic_sample_titv')
    with op.batch_alter_table('journal_exome_somatic_gene_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_gene_interaction_gene2'))
        batch_op.drop_index(batch_op.f('ix_journal_exome_somatic_gene_interaction_gene1'))
        batch_op.drop_index('index_journal_exome_somatic_gene_interation')

    op.drop_table('journal_exome_somatic_gene_interaction')
    op.drop_table('patient_barcode')
    op.drop_table('pathway')
    op.drop_table('genelist')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_token'))

    op.drop_table('api_tokens')
    # ### end Alembic commands ###
