"""Add oncoplot esjournal

Revision ID: e36dfc9f1b6e
Revises: 8b5a4c0bb0b6
Create Date: 2025-10-23 18:32:13.848909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36dfc9f1b6e'
down_revision: Union[str, Sequence[str], None] = '8b5a4c0bb0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('es_journal_oncoplot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gene', sa.String(length=20), nullable=True),
    sa.Column('sample_id', sa.String(length=20), nullable=True),
    sa.Column('evalue', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('es_journal_oncoplot')
    # ### end Alembic commands ###
