"""Renamed table2

Revision ID: ec2c08fc58e1
Revises: efa29a9aa8b9
Create Date: 2025-11-01 19:10:16.970551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2c08fc58e1'
down_revision: Union[str, Sequence[str], None] = 'efa29a9aa8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomic_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chr_pos'))
        batch_op.drop_index(batch_op.f('ix_genomic_position_chromosome'))
        batch_op.drop_index(batch_op.f('ix_genomic_position_position'))

    op.drop_table('genomic_position')
    op.drop_table('somatic_genomic_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('somatic_genomic_position',
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chromosome', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genomic_position',
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chromosome', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genomic_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genomic_position_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_genomic_position_chromosome'), ['chromosome'], unique=False)
        batch_op.create_index(batch_op.f('idx_chr_pos'), ['chromosome', 'position'], unique=False)

    # ### end Alembic commands ###
