"""Create somatic positions autocomplete

Revision ID: efa29a9aa8b9
Revises: 509f9d2933f2
Create Date: 2025-11-01 19:06:27.871132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa29a9aa8b9'
down_revision: Union[str, Sequence[str], None] = '509f9d2933f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genomic_position',
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chromosome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genomic_position', schema=None) as batch_op:
        batch_op.create_index('idx_chr_pos', ['chromosome', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_genomic_position_chromosome'), ['chromosome'], unique=False)
        batch_op.create_index(batch_op.f('ix_genomic_position_position'), ['position'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomic_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genomic_position_position'))
        batch_op.drop_index(batch_op.f('ix_genomic_position_chromosome'))
        batch_op.drop_index('idx_chr_pos')

    op.drop_table('genomic_position')
    # ### end Alembic commands ###
